# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Product2
  product: Product2
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Дисциплина 1
    output: web, pdf
    folderitems:

    - title: статья 1
      url: /p1_sample1.html
      output: web
    - title: статья 2
      url: /p1_sample1.html
      output: web

  - title: Дисциплина 2
    output: web, pdf
    folderitems:

    - title: Статья 1
      url: /p1_sample1.html
      output: web, pdf

    - title: Статья 2
      url: /p1_sample1.html
      output: web, pdf

    - title: Статья 3
      url: /p1_sample1.html
      output: web, pdf

    - title: Статья 4
      url: /p1_sample1.html
      output: web, pdf

    - title: Статья 5
      url: /p1_sample1.html
      output: web, pdf

  - title: Дисциплина 3
    output: web, pdf
    folderitems:

    - title: Статья 1
      url: /p1_sample1.html
      output: web, pdf

    - title: Статья 2
      url: /p1_sample1.html
      output: web, pdf

    - title: Статья 3
      url: /p1_sample1.html
      output: web, pdf

    - title: Статья 4
      url: /p1_sample1.html
      output: web, pdf

