# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Product2
  product: Product2
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: УРОКИ EXCEL ДЛЯ ЧАЙНИКОВ И НАЧИНАЮЩИХ ПОЛЬЗОВАТЕЛЕЙ
    output: web, pdf
    folderitems:

    - title: Подготовка к работе
      url: /p2_sample1.html
      output: web

    - title: Управление листами и заполнение ячеек данными
      url: /p2_sample2.html
      output: web

    - title: Операции с книгами, листами и файлами
      url: /p2_sample3.html
      output: web

    - title: Диапазоны ячеек смежные и несмежные
      url: /p2_landing_page.html
      output: web

    - title: Редактирование данных листа
      url: /p2_landing_page.html
      output: web

    - title: Форматирование ячеек таблицы
      url: /p2_landing_page.html
      output: web

    - title: Формулы и функции
      url: /p2_landing_page.html
      output: web

    - title: Графики и диаграммы
      url: /p2_landing_page.html
      output: web

    - title: Просмотр и печать документов
      url: /p2_landing_page.html
      output: web

  - title: САМОУЧИТЕЛЬ EXCEL С ПРИМЕРАМИ ДЛЯ ПОЛЬЗОВАТЕЛЕЙ СРЕДНЕГО УРОВНЯ
    output: web, pdf
    folderitems:

    - title: Решения проблем с введением данных в ячейки
      url: /p2_sample1.html
      output: web, pdf

    - title: Автоматическое заполнение ячеек таблиц
      url: /p2_sample2.html
      output: web, pdf

    - title: Форматирование ячеек
      url: /p2_sample3.html
      output: web, pdf

    - title: Защита данных
      url: /p2_sample4.html
      output: web, pdf

    - title: Работа с таблицами
      url: /p2_sample5.html
      output: web, pdf
    
    - title: Формулы в Excel
      url: /p2_sample5.html
      output: web, pdf

    - title: Имена диапазонов ячеек
      url: /p2_sample5.html
      output: web, pdf

    - title: Создание диаграмм и графиков в Excel
      url: /p2_sample5.html
      output: web, pdf

    - title: Подбор параметра, поиск решения и сценарии
      url: /p2_sample5.html
      output: web, pdf

    - title: Подбор параметра, поиск решения и сценарии
      url: /p2_sample5.html
      output: web, pdf

