# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.


entries:
- title: Sidebar
  product: Product1
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: 1 Семестр
    output: web, pdf
    folderitems:
   - title: Дисциплина 1
     output: web, pdf
     folderitems:
     -title: Статья 1
      url: www.yandex.ru #p1_landing_page.html
      output: web
     -title: Статья 2
      url: /p1_landing_page.html
      output: web
     -title: Статья 3
      url: /p1_landing_page.html
      output: web

    - title: Дисциплина 1
      #url: /p1_sample1.html
      output: web, pdf
      folderitems:
      -title: Статья 1
       url: /p1_landing_page.html
       output: web
      -title: Статья 2
       url: /p1_landing_page.html
       output: web
      
      

   # - title: Sample 2
    #  url: /p1_sample2.html
   #   output: web, pdf

  
