# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Product2
  product: Product2
  version: 1.0
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage
      output: pdf
      type: frontmatter

  - title: Дисциплина 1
    output: web, pdf
    folderitems:

    - title: УРОКИ EXCEL ДЛЯ ЧАЙНИКОВ И НАЧИНАЮЩИХ ПОЛЬЗОВАТЕЛЕЙ
      url: /p1_sample1.html
      output: web
    - title: САМОУЧИТЕЛЬ EXCEL С ПРИМЕРАМИ ДЛЯ ПОЛЬЗОВАТЕЛЕЙ СРЕДНЕГО УРОВНЯ
      url: /p1_sample2.html
      output: web

  - title: Дисциплина 2
    output: web, pdf
    folderitems:

    - title: Статья 1
      url: /p2_sample1.html
      output: web, pdf

    - title: Статья 2
      url: /p2_sample2.html
      output: web, pdf

    - title: Статья 3
      url: /p2_sample3.html
      output: web, pdf

    - title: Статья 4
      url: /p2_sample4.html
      output: web, pdf

    - title: Статья 5
      url: /p2_sample5.html
      output: web, pdf

  - title: Дисциплина 3
    output: web, pdf
    folderitems:

    - title: Статья 1
      url: /p2_sample6.html
      output: web, pdf

    - title: Статья 2
      url: /p2_sample7.html
      output: web, pdf

    - title: Статья 3
      url: /p2_sample8.html
      output: web, pdf

    - title: Статья 4
      url: /p2_sample9.html
      output: web, pdf

    - title: Статья 5
      url: /p2_sample10.html
      output: web, pdf

    - title: Статья 6
      url: /p2_sample11.html
      output: web, pdf

    - title: Статья 7
      url: /p2_sample12.html
      output: web, pdf

    - title: Статья 8
      url: /p2_sample13.html
      output: web, pdf

    - title: Статья 9
      url: /p2_sample14.html
      output: web, pdf
